import { useState } from 'react';
import { Navigate, NavLink, Outlet, useLocation } from 'react-router-dom';
import { LayoutDashboard, Package, Files, UsersRound, Settings, Plus, LogOut, Menu, X, ArrowUpRight, Leaf } from 'lucide-react';
import { useApp, messageOf } from './AppProvider';
import { BrandLogo, Loading } from './ui';
const links=[['/','Dashboard',LayoutDashboard],['/listino','Listino',Package],['/preventivi','Preventivi',Files],['/clienti','Clienti',UsersRound],['/impostazioni','Impostazioni',Settings]] as const;
export default function Layout(){
  const app=useApp();const [open,setOpen]=useState(false);const location=useLocation();
  if(!app.ready)return <Loading/>;if(!app.user)return <Navigate to="/login" replace/>;
  const section=links.find(([path])=>path==='/'?location.pathname==='/':location.pathname.startsWith(path))?.[1]??'Preventivi';
  return <div className="app-shell"><a className="skip-link" href="#main-content">Vai al contenuto</a>{open&&<button className="sidebar-backdrop" aria-label="Chiudi menu" onClick={()=>setOpen(false)}/>}<aside className={`sidebar ${open?'sidebar-open':''}`}><NavLink to="/" className="sidebar-brand" onClick={()=>setOpen(false)}><BrandLogo/></NavLink><div className="workspace-label">AREA PREVENTIVI <span>WORKSPACE</span></div><NavLink className="btn btn-primary sidebar-create" to="/preventivi/nuovo" onClick={()=>setOpen(false)}><Plus size={18}/> Nuovo preventivo</NavLink><div className="nav-caption">IL TUO SPAZIO</div><nav aria-label="Navigazione principale">{links.map(([path,label,Icon])=><NavLink key={path} end={path==='/'} to={path} className={({isActive})=>`nav-link ${isActive?'active':''}`} onClick={()=>setOpen(false)}><Icon size={19}/><span>{label}</span>{label==='Preventivi'&&app.data&&<small>{app.data.quotes.length}</small>}</NavLink>)}</nav><div className="sidebar-bottom"><div className="sidebar-note"><Leaf size={20}/><p>Energia, comfort<br/><strong>e impianti integrati.</strong></p><a href="https://www.green-flux.com/" target="_blank" rel="noreferrer" aria-label="Visita il sito Green Flux"><ArrowUpRight size={16}/></a></div><button className="nav-link logout" onClick={()=>app.logout().catch(err=>app.notify(messageOf(err),'error'))}><LogOut size={18}/> Esci dall’area</button></div></aside><div className="app-content"><header className="topbar"><div className="topbar-left"><button className="btn btn-icon mobile-menu" onClick={()=>setOpen(!open)} aria-label={open?'Chiudi menu':'Apri menu'}>{open?<X size={21}/>:<Menu size={21}/>}</button><span className="breadcrumb">Area di lavoro <span>/</span> <strong>{section}</strong></span></div><div className="topbar-right">{app.isDemo&&<span className="demo-indicator"><span/> Modalità demo</span>}<span className="avatar">GF</span><span className="user-label">{app.isDemo?'Team Green Flux':app.user}<small>{app.isDemo?'Archivio locale':'Archivio condiviso'}</small></span></div></header><main id="main-content" className="main-content">{app.loading?<Loading text="Preparazione dell’archivio…"/>:app.error?<div className="card access-error"><h1>Archivio non disponibile</h1><p>{app.error}</p><button className="btn btn-primary" onClick={()=>app.refresh().catch(err=>app.notify(messageOf(err),'error'))}>Riprova</button><p className="muted">Per l’accesso aziendale, l’account deve essere abilitato dall’amministratore in Supabase.</p></div>:app.data?<Outlet/>:<Loading/>}</main><footer className="app-footer"><span>GREEN FLUX <span className="muted">/ Area Preventivi</span></span><span>{app.isDemo?'Dati DEMO · Prezzi puramente illustrativi':'Il tuo spazio di lavoro'}</span></footer></div></div>;
}
